import { chromium } from 'playwright'
const out = process.argv[2]
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const errors = []
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
await page.goto('http://localhost:4173/')
await page.evaluate(() => localStorage.clear())
await page.reload()
await page.waitForTimeout(800)
await page.click('text=Plan from your needs')
await page.waitForTimeout(300)
await page.click('[aria-label="Bedrooms"] >> text=4')
await page.click('[aria-label="Bathrooms"] >> text=2.5')
await page.click('[aria-label="Floors"] >> text=Two')
await page.click('text=Home office')
await page.waitForTimeout(300)
await page.screenshot({ path: `${out}/brief-form.png` })
await page.click('text=Make my plan')
await page.waitForTimeout(3000)
await page.screenshot({ path: `${out}/brief-split.png` })
await page.click('.view-switch >> text=3D')
await page.click('.bar3d >> text=Explode')
await page.waitForTimeout(3500)
await page.screenshot({ path: `${out}/brief-explode.png` })
await page.click('.bar3d >> text=Explode')
await page.click('.bar3d >> text=Outside')
await page.waitForTimeout(2500)
await page.screenshot({ path: `${out}/brief-outside.png` })
console.log(errors.join('\n') || 'no errors')
await browser.close()
