import { chromium } from 'playwright'
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } })
const errors = []
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
await page.goto('http://localhost:4174/')
await page.evaluate(() => { localStorage.clear(); localStorage.setItem('threshold:welcomed', '1') })
await page.reload()
await page.waitForTimeout(800)
await page.click('.plan-badge')
const href = await page.locator('.plan-card a.btn').first().getAttribute('href')
console.log('checkout link:', href)
await page.goto('http://localhost:4174/?checkout_session=cs_test_e2e')
await page.waitForTimeout(2000)
console.log('toast:', await page.locator('.toast').first().textContent().catch(() => 'none'))
console.log('badge:', await page.locator('.plan-badge').textContent())
console.log('url after:', page.url())
console.log(errors.join('\n') || 'no errors')
await browser.close()
