import { chromium } from 'playwright'
const out = process.argv[2]
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('pageerror', (e) => console.log('pageerror: ' + e.message))
await page.goto('http://localhost:4173/')
await page.waitForTimeout(1200)
await page.click('.view-switch >> text=2D')
await page.waitForTimeout(400)
const box = await (await page.$('.plan-svg')).boundingBox()
const P = (fx, fy) => ({ x: box.x + box.width * fx, y: box.y + box.height * fy })
await page.keyboard.press('w')
let d = P(0.2, 0.9)
await page.mouse.move(d.x, d.y)
await page.mouse.click(d.x, d.y)
await page.waitForTimeout(200)
d = P(0.5, 0.9)
await page.mouse.move(d.x, d.y, { steps: 4 })
await page.waitForTimeout(200)
await page.keyboard.type('10', { delay: 80 })
await page.waitForTimeout(200)
console.log('input:', await page.evaluate(() => document.querySelector('#len-entry')?.value ?? 'none'), 'focused:', await page.evaluate(() => document.activeElement?.id))
await page.screenshot({ path: `${out}/20-typing.png` })
await page.keyboard.press('Enter')
await page.waitForTimeout(200)
await page.screenshot({ path: `${out}/21-after-enter.png` })
await page.keyboard.press('Enter')
await page.waitForTimeout(300)
console.log('walls:', await page.evaluate(() => JSON.stringify(Object.keys(localStorage))))
await browser.close()
