import { chromium } from 'playwright'
const out = process.argv[2]
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const errors = []
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
page.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('ERR_CERT')) errors.push(m.text()) })
await page.goto('http://localhost:4173/')
await page.evaluate(() => localStorage.clear())
await page.reload()
await page.waitForTimeout(800)
if (await page.$('.welcome')) await page.click('text=Explore the example home')
await page.waitForTimeout(1200)
await page.click('.view-switch >> text=3D')
await page.click('.bar3d >> text=Outside')
await page.selectOption('#view-from', 'E')
await page.waitForTimeout(4000)
await page.screenshot({ path: `${out}/ext3-east.png` })
await page.fill('#sun-hour', '21.5')
await page.selectOption('#view-from', 'street')
await page.waitForTimeout(4000)
await page.screenshot({ path: `${out}/ext3-night.png` })
await page.fill('#sun-hour', '15')
await page.click('.view-switch >> text=Walk')
await page.waitForTimeout(3000)
await page.screenshot({ path: `${out}/ext3-walk.png` })
await page.click('.view-switch >> text=3D')
await page.click('.bar3d >> text=Explode')
await page.waitForTimeout(3500)
await page.screenshot({ path: `${out}/ext3-explode.png` })
await page.click('.bar3d >> text=Explode')
await page.click('text=Fast 3D')
await page.waitForTimeout(3500)
await page.screenshot({ path: `${out}/ext3-fast.png` })
console.log(errors.slice(0, 10).join('\n') || 'no errors')
await browser.close()
