import { chromium } from 'playwright'
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('pageerror', (e) => console.log('pageerror: ' + e.message))
await page.goto('http://localhost:4173/')
await page.waitForTimeout(800)
if (await page.$('.welcome')) await page.click('text=Explore the example home')
await page.click('.help-btn')
await page.click('text=Lexend')
const r = await page.evaluate(() => ({ cls: document.documentElement.className, link: !!document.getElementById('font-lexend'), font: getComputedStyle(document.body).fontFamily, saved: localStorage.getItem('threshold:comfort') }))
console.log(JSON.stringify(r))
await page.reload()
await page.waitForTimeout(500)
console.log(await page.evaluate(() => document.documentElement.className))
await browser.close()
