import { chromium } from 'playwright'
const out = process.argv[2]
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('pageerror', (e) => console.log('pageerror: ' + e.message))
await page.goto('http://localhost:4173/')
await page.waitForTimeout(800)
if (await page.$('.welcome')) await page.click('text=Start from scratch')
await page.click('.view-switch >> text=2D')
const box = await (await page.$('.plan-svg')).boundingBox()
const drag = async (a, b) => { await page.mouse.move(box.x + box.width * a[0], box.y + box.height * a[1]); await page.mouse.down(); await page.mouse.move(box.x + box.width * b[0], box.y + box.height * b[1], { steps: 8 }); await page.mouse.up(); await page.waitForTimeout(200) }
await page.keyboard.press('r')
await drag([0.2, 0.2], [0.5, 0.75])
await page.click('.chip >> text=Bedroom')
await page.click('text=Furnish this room')
await page.keyboard.press('r')
await drag([0.5, 0.2], [0.85, 0.75])
await page.click('.chip >> text=Living room')
await page.click('text=Furnish this room')
// Doors between and to outside
await page.keyboard.press('d')
await page.mouse.click(box.x + box.width * 0.5, box.y + box.height * 0.6)
await page.mouse.click(box.x + box.width * 0.7, box.y + box.height * 0.75)
await page.keyboard.press('Escape')
const st = await page.evaluate(() => window.__threshold.store.getState().project.levels[0].items.map((i) => i.type))
console.log(JSON.stringify(st))
await page.click('.view-switch >> text=Split')
await page.waitForTimeout(2500)
await page.screenshot({ path: `${out}/g1-furnished.png` })
await browser.close()
