import { chromium } from 'playwright'
const out = process.argv[2]
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('pageerror', (e) => console.log('pageerror: ' + e.message))
await page.goto('http://localhost:4173/')
await page.waitForTimeout(800)
if (await page.$('.welcome')) await page.click('text=Explore the example home')
await page.click('.view-switch >> text=2D')
await page.keyboard.press('m')
const box = await (await page.$('.plan-svg')).boundingBox()
await page.mouse.move(box.x + box.width * 0.2, box.y + box.height * 0.8)
await page.mouse.down()
await page.mouse.move(box.x + box.width * 0.6, box.y + box.height * 0.8, { steps: 8 })
await page.mouse.up()
await page.waitForTimeout(200)
await page.click('text=Keep on plan')
await page.waitForTimeout(200)
console.log('dims', await page.evaluate(() => (window.__threshold.store.getState().project.levels[0].dims ?? []).length))
await page.keyboard.press('Escape')
await page.screenshot({ path: `${out}/f1-keptdim.png` })
await browser.close()
