import { chromium } from 'playwright'
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const errors = []
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
await page.goto('http://localhost:4173/')
await page.evaluate(() => localStorage.clear())
await page.reload()
await page.waitForTimeout(800)
await page.click('text=Start from scratch')
await page.waitForTimeout(600)
await page.click('.view-switch >> text=2D')
const box = await page.locator('svg.plan, .plan-wrap svg').first().boundingBox()
await page.mouse.move(box.x + box.width * 0.3, box.y + box.height * 0.3)
await page.mouse.down()
await page.mouse.move(box.x + box.width * 0.6, box.y + box.height * 0.7, { steps: 8 })
await page.mouse.up()
await page.keyboard.press('v')
await page.waitForTimeout(300)
const area = page.locator('[data-hit^="rl:area:"]').first()
const b0 = await area.boundingBox()
await page.mouse.move(b0.x + b0.width / 2, b0.y + b0.height / 2)
await page.mouse.down()
await page.mouse.move(b0.x + b0.width / 2 + 120, b0.y + b0.height / 2 + 40, { steps: 8 })
await page.mouse.up()
await page.waitForTimeout(300)
const b1 = await page.locator('[data-hit^="rl:area:"]').first().boundingBox()
console.log('label moved by', Math.round(b1.x - b0.x), Math.round(b1.y - b0.y), '| editor open:', await page.locator('.label-edit').count())
console.log(errors.join('\n') || 'no errors')
await browser.close()
