import { chromium } from 'playwright'
const out = process.argv[2]
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const errors = []
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
await page.goto('http://localhost:4173/')
await page.evaluate(() => localStorage.clear())
await page.reload()
await page.waitForTimeout(800)
await page.click('text=Start from scratch')
await page.waitForTimeout(600)
await page.click('.view-switch >> text=2D')
await page.waitForTimeout(400)
// Draw one room with the Room tool.
const box = await page.locator('svg.plan, .plan-wrap svg').first().boundingBox()
await page.mouse.move(box.x + box.width * 0.3, box.y + box.height * 0.3)
await page.mouse.down()
await page.mouse.move(box.x + box.width * 0.6, box.y + box.height * 0.7, { steps: 8 })
await page.mouse.up()
await page.keyboard.press('v')
await page.waitForTimeout(400)
const dims = page.locator('[data-hit^="rl:dims:"]').first()
console.log('dims before:', await dims.textContent())
await dims.click()
await page.waitForTimeout(200)
await page.screenshot({ path: `${out}/label-edit-open.png` })
await page.keyboard.type(`20' x 15'`)
await page.keyboard.press('Enter')
await page.waitForTimeout(300)
console.log('dims after:', await page.locator('[data-hit^="rl:dims:"]').first().textContent())
console.log('area after:', await page.locator('[data-hit^="rl:area:"]').first().textContent())
// Area
await page.locator('[data-hit^="rl:area:"]').first().click()
await page.keyboard.type('600')
await page.keyboard.press('Enter')
await page.waitForTimeout(300)
console.log('area after 600:', await page.locator('[data-hit^="rl:area:"]').first().textContent(), '| dims:', await page.locator('[data-hit^="rl:dims:"]').first().textContent())
// Bad input keeps the box open with a hint
await page.locator('[data-hit^="rl:dims:"]').first().click()
await page.keyboard.type('banana')
await page.keyboard.press('Enter')
await page.waitForTimeout(200)
console.log('hint:', await page.locator('.label-edit-hint').textContent())
await page.keyboard.press('Escape')
// Name
await page.locator('[data-hit^="rl:name:"]').first().click()
await page.keyboard.type('Great room')
await page.keyboard.press('Enter')
await page.waitForTimeout(300)
console.log('name:', await page.locator('[data-hit^="rl:name:"]').first().textContent())
// Undo restores the previous name
await page.keyboard.press('Control+z')
await page.waitForTimeout(300)
console.log('after undo:', await page.locator('[data-hit^="rl:name:"]').first().textContent())
// Wall lengths follow the room
const wallLens = await page.$$eval('.wall-dim, .dim-text', (els) => els.map((e) => e.textContent).slice(0, 6))
console.log('wall dims:', JSON.stringify(wallLens))
await page.screenshot({ path: `${out}/label-edit-done.png` })
console.log(errors.join('\n') || 'no errors')
await browser.close()
