import { chromium } from 'playwright'
const out = process.argv[2]
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const errors = []
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
await page.goto('http://localhost:4173/')
await page.waitForTimeout(800)
if (await page.$('.welcome')) await page.click('text=Explore the example home')
await page.waitForTimeout(1200)
await page.click('button:has-text("Project")')
await page.click('text=Show the lot and setbacks')
await page.waitForTimeout(400)
await page.click('.zoom-btns [aria-label="Zoom out"]')
await page.waitForTimeout(400)
await page.locator('#lot-w').scrollIntoViewIfNeeded()
await page.screenshot({ path: `${out}/lot-split.png` })
// Tighten the front setback so the design check complains.
await page.fill('#lot-front', '60')
await page.press('#lot-front', 'Enter')
await page.waitForTimeout(300)
await page.click('button:has-text("Edit")')
await page.waitForTimeout(300)
const checks = await page.$$eval('.check-item', (els) => els.map((e) => e.textContent))
console.log(JSON.stringify(checks.slice(0, 4)))
await page.click('.view-switch >> text=3D')
await page.click('.bar3d >> text=Outside')
await page.waitForTimeout(2500)
await page.screenshot({ path: `${out}/lot-3d.png` })
console.log(errors.join('\n') || 'no errors')
await browser.close()
