// Product screenshots for the landing page: node scripts/marketing-shots.mjs public/shots
import { chromium } from 'playwright'
const out = process.argv[2] ?? 'public/shots'
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 }, deviceScaleFactor: 1 })
const shot = async (name, wait = 3500) => {
  await page.waitForTimeout(wait)
  await page.screenshot({ path: `${out}/${name}.jpg`, type: 'jpeg', quality: 82 })
}
await page.goto('http://localhost:4173/')
await page.evaluate(() => localStorage.clear())
await page.reload()
await page.waitForTimeout(800)
await page.click('text=Explore the example home')
await page.waitForTimeout(1000)
await page.click('.view-switch >> text=3D')
await page.selectOption('#view-from', 'street')
await shot('street', 5000)
await page.fill('#sun-hour', '20.5')
await shot('night', 4500)
await page.fill('#sun-hour', '15')
await page.selectOption('#view-from', 'corner')
await page.click('.bar3d >> text=Explode')
await shot('explode', 5000)
await page.click('.bar3d >> text=Explode')
await page.click('.bar3d >> text=Inside')
await shot('inside', 4500)
await page.click('.view-switch >> text=Walk')
await shot('walk', 4500)
await page.click('.view-switch >> text=Split')
await page.click('button:has-text("Budget")')
await page.click('text=Shopping list')
await shot('split', 4500)
await page.click('.view-switch >> text=2D')
await page.click('button:has-text("Edit")')
await shot('plan', 2000)
await browser.close()
console.log('done')
