// Shift-click two chairs in the plan, drag them together, align them, undo.
import { chromium } from 'playwright'
const out = process.argv[2]
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('pageerror', (e) => console.log('pageerror: ' + e.message))
await page.goto('http://localhost:4173/')
await page.waitForTimeout(800)
if (await page.$('.welcome')) await page.click('text=Explore the example home')
await page.click('.view-switch >> text=2D')
await page.waitForTimeout(600)
const toScreen = (pt) => page.evaluate(({ x, y }) => {
  const svg = document.querySelector('.plan-svg')
  const [vx, vy, vw, vh] = svg.getAttribute('viewBox').split(' ').map(Number)
  const r = svg.getBoundingClientRect()
  return { x: r.left + ((x - vx) / vw) * r.width, y: r.top + ((y - vy) / vh) * r.height }
}, pt)
const chairs = await page.evaluate(() => window.__threshold.store.getState().project.levels[0].items.filter((i) => i.type === 'chair').slice(0, 2))
const a = await toScreen(chairs[0]); const b = await toScreen(chairs[1])
await page.mouse.click(a.x, a.y)
await page.keyboard.down('Shift'); await page.mouse.click(b.x, b.y); await page.keyboard.up('Shift')
await page.waitForTimeout(200)
console.log('multi', await page.evaluate(() => window.__threshold.store.getState().multi.length))
await page.mouse.move(a.x, a.y); await page.mouse.down(); await page.mouse.move(a.x + 30, a.y + 10, { steps: 5 }); await page.mouse.move(a.x + 60, a.y + 20, { steps: 5 }); await page.mouse.up()
await page.waitForTimeout(200)
const moved = await page.evaluate((ids) => window.__threshold.store.getState().project.levels[0].items.filter((i) => ids.includes(i.id)).map((i) => [Math.round(i.x), Math.round(i.y)]), chairs.map((c) => c.id))
console.log('before', JSON.stringify(chairs.map((c) => [Math.round(c.x), Math.round(c.y)])), 'after', JSON.stringify(moved))
await page.click('text=Tops')
await page.waitForTimeout(200)
const aligned = await page.evaluate((ids) => window.__threshold.store.getState().project.levels[0].items.filter((i) => ids.includes(i.id)).map((i) => Math.round(i.y)), chairs.map((c) => c.id))
console.log('aligned y', JSON.stringify(aligned))
await page.screenshot({ path: `${out}/50-multi.png` })
// Box select
await page.keyboard.press('Escape')
const t = await page.evaluate(() => window.__threshold.store.getState().project.levels[0].items.find((i) => i.type === 'table-6'))
const c1 = await toScreen({ x: t.x - 150, y: t.y - 150 }); const c2 = await toScreen({ x: t.x + 150, y: t.y + 150 })
await page.keyboard.down('Shift'); await page.mouse.move(c1.x, c1.y); await page.mouse.down(); await page.mouse.move(c2.x, c2.y, { steps: 6 }); await page.mouse.up(); await page.keyboard.up('Shift')
console.log('box selected', await page.evaluate(() => window.__threshold.store.getState().multi.length))
await browser.close()
