import { chromium } from 'playwright'
const out = process.argv[2]
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('pageerror', (e) => console.log('pageerror: ' + e.message))
await page.goto('http://localhost:4173/')
await page.waitForTimeout(800)
if (await page.$('.welcome')) await page.click('text=Explore the example home')
await page.click('.view-switch >> text=3D')
await page.evaluate(() => window.__threshold.store.setState({ sunHour: 21.5 }))
await page.waitForTimeout(2500)
await page.screenshot({ path: `${out}/70-night-inside.png` })
await page.click('text=Outside')
await page.waitForTimeout(2000)
await page.screenshot({ path: `${out}/71-night-outside.png` })
await browser.close()
