import { chromium } from 'playwright'
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } })
const page = await ctx.newPage()
const errors = []
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
await page.goto('http://localhost:4173/')
await page.waitForTimeout(800)
if (await page.$('.welcome')) await page.click('text=Explore the example home')
await page.waitForTimeout(1500)
const reg = await page.evaluate(async () => { const r = await navigator.serviceWorker.getRegistration(); return !!r?.active })
console.log('service worker active:', reg)
await page.reload()
await page.waitForTimeout(1500)
const manifest = await page.evaluate(async () => (await fetch('manifest.webmanifest')).ok)
console.log('manifest:', manifest)
await ctx.setOffline(true)
await page.reload()
await page.waitForTimeout(2500)
console.log('offline reload shows app:', await page.locator('.topbar').count(), 'title:', await page.title())
await ctx.setOffline(false)
console.log(errors.join('\n') || 'no errors')
await browser.close()
