import { chromium } from 'playwright'
const out = process.argv[2]
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('pageerror', (e) => console.log('pageerror: ' + e.message))
await page.goto('http://localhost:4173/')
await page.waitForTimeout(800)
if (await page.$('.welcome')) await page.click('text=Explore the example home')
await page.click('.view-switch >> text=2D')
await page.waitForTimeout(400)
const toScreen = (pt) => page.evaluate(({ x, y }) => {
  const svg = document.querySelector('.plan-svg')
  const [vx, vy, vw, vh] = svg.getAttribute('viewBox').split(' ').map(Number)
  const r = svg.getBoundingClientRect()
  return { x: r.left + ((x - vx) / vw) * r.width, y: r.top + ((y - vy) / vh) * r.height }
}, pt)
// Patio north of the house (y < 0), floor only
await page.click('[aria-label="Zoom out"]')
await page.click('[aria-label="Zoom out"]')
await page.waitForTimeout(200)
await page.keyboard.press('r')
await page.click('text=Floor only')
const ft = 30.48
let a = await toScreen({ x: 2 * ft, y: -14 * ft }), b = await toScreen({ x: 30 * ft, y: -1 * ft })
await page.mouse.move(a.x, a.y); await page.mouse.down(); await page.mouse.move(b.x, b.y, { steps: 8 }); await page.mouse.up()
await page.waitForTimeout(300)
const place = async (name, x, y) => {
  await page.keyboard.press('f')
  await page.fill('#catalog-search', name)
  await page.click(`.cat-card >> text=${name}`)
  const p = await toScreen({ x: x * ft, y: y * ft })
  await page.mouse.move(p.x, p.y); await page.waitForTimeout(80); await page.mouse.click(p.x, p.y)
  await page.waitForTimeout(150)
}
await place('Pergola', 10, -8)
await place('Fire pit', 23, -8)
await place('Garden bed', 27, -12)
await place('Patio umbrella', 17, -5)
const st = await page.evaluate(() => { const l = window.__threshold.store.getState().project.levels[0]; const r = l.rooms[l.rooms.length - 1]; return { area: r.name, floor: r.floor, walls: l.walls.length, items: l.items.slice(-4).map((i) => i.type) } })
console.log(JSON.stringify(st))
await page.click('.view-switch >> text=3D')
await page.click('text=Outside')
await page.waitForTimeout(2500)
await page.screenshot({ path: `${out}/90-outdoor.png` })
await page.click('.view-switch >> text=2D')
await page.click('.level-chips >> text=Upper floor')
await page.waitForTimeout(500)
await page.screenshot({ path: `${out}/91-upper.png` })
await browser.close()
