import { chromium } from 'playwright'
const out = process.argv[2]
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const errors = []
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
await page.goto('http://localhost:4173/')
await page.waitForTimeout(800)
if (await page.$('.welcome')) await page.click('text=Explore the example home')
await page.waitForTimeout(1500)
await page.click('.view-switch >> text=3D')
await page.waitForTimeout(1500)
await page.click('.bar3d >> text=Explode')
await page.waitForTimeout(3000)
await page.click('.part-toggles >> text=Roof')
await page.click('.part-toggles >> text=Walls')
await page.waitForTimeout(1500)
await page.screenshot({ path: `${out}/parts-nowalls.png` })
await page.click('.part-toggles >> text=Walls')
await page.click('.part-toggles >> text=Furniture')
await page.waitForTimeout(1500)
await page.screenshot({ path: `${out}/parts-nofurn.png` })
console.log(errors.join('\n') || 'no errors')
await browser.close()
