import { chromium } from 'playwright'
const out = process.argv[2]
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('pageerror', (e) => console.log('pageerror: ' + e.message))
await page.goto('http://localhost:4173/')
await page.waitForTimeout(800)
if (await page.$('.welcome')) await page.click('text=Explore the example home')
await page.click('.panel-tabs >> text=Project')
await page.click('.template-card >> text=Single-storey ranch')
await page.click('text=Click again')
await page.waitForTimeout(600)
await page.click('.view-switch >> text=2D')
await page.waitForTimeout(600)
await page.screenshot({ path: `${out}/b1-ranch-plan.png` })
await page.click('.view-switch >> text=3D')
await page.waitForTimeout(2500)
await page.screenshot({ path: `${out}/b2-ranch-inside.png` })
await page.click('text=Outside')
await page.waitForTimeout(2000)
await page.screenshot({ path: `${out}/b3-ranch-outside.png` })
await browser.close()
