import { chromium } from 'playwright'
const out = process.argv[2]
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const errors = []
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
page.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('ERR_CERT')) errors.push(m.text()) })
await page.goto('http://localhost:4173/')
await page.waitForTimeout(800)
if (await page.$('.welcome')) await page.click('text=Explore the example home')
await page.waitForTimeout(1200)
await page.click('.view-switch >> text=3D')
await page.waitForTimeout(1500)
await page.click('.bar3d >> text=Section')
await page.waitForTimeout(2500)
await page.screenshot({ path: `${out}/section-z.png` })
await page.click('.bar3d >> text=Side to side')
await page.fill('#section-at', '0.3')
await page.waitForTimeout(2500)
await page.screenshot({ path: `${out}/section-x.png` })
await page.click('.bar3d >> text=Section')
await page.waitForTimeout(1500)
await page.screenshot({ path: `${out}/section-off.png` })
console.log(errors.join('\n') || 'no errors')
await browser.close()
