import { chromium } from 'playwright'
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 }, permissions: ['clipboard-read', 'clipboard-write'] })
const page = await ctx.newPage()
const errors = []
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
await page.goto('http://localhost:4173/')
await page.evaluate(() => localStorage.clear())
await page.reload()
await page.waitForTimeout(800)
await page.click('text=Explore the example home')
await page.waitForTimeout(800)
await page.click('button:has-text("Project")')
console.log('meter:', (await page.locator('.allowance').textContent()).replace(/\s+/g, ' '))
await page.click('text=Copy share link')
await page.waitForTimeout(500)
const link = await page.evaluate(() => navigator.clipboard.readText())
console.log('link length:', link.length, link.slice(0, 40))
// A different person opens it.
const other = await (await browser.newContext({ viewport: { width: 1280, height: 800 } })).newPage()
other.on('pageerror', (e) => errors.push('other: ' + e.message))
await other.goto(link)
await other.waitForTimeout(2500)
console.log('welcome shown:', await other.locator('.welcome').count())
console.log('title:', await other.locator('.project-title input, .project-title').first().textContent().catch(() => ''), await other.evaluate(() => document.title))
console.log('toast:', await other.locator('.toast').first().textContent().catch(() => 'none'))
console.log('hash cleared:', !other.url().includes('#design='))
console.log(errors.join('\n') || 'no errors')
await browser.close()
