import { chromium } from 'playwright'
const out = process.argv[2]
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, acceptDownloads: true })
const page = await ctx.newPage()
const errors = []
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
await page.goto('http://localhost:4173/')
await page.waitForTimeout(800)
if (await page.$('.welcome')) await page.click('text=Explore the example home')
await page.waitForTimeout(1500)
await page.click('button:has-text("Budget")')
await page.waitForTimeout(400)
await page.click('text=Shopping list')
await page.waitForTimeout(600)
await page.screenshot({ path: `${out}/shop-1.png` })
const [dl] = await Promise.all([page.waitForEvent('download', { timeout: 5000 }), page.click('text=Save as spreadsheet')])
const path = await dl.path()
const fs = await import('node:fs')
const csv = fs.readFileSync(path, 'utf8')
console.log(dl.suggestedFilename(), csv.split('\n').length - 1, 'rows')
console.log(csv.split('\n').slice(0, 8).join('\n'))
await page.setViewportSize({ width: 390, height: 844 })
await page.waitForTimeout(800)
await page.screenshot({ path: `${out}/shop-phone.png` })
console.log(errors.join('\n') || 'no errors')
await browser.close()
