import { chromium } from 'playwright'
import { readFileSync, writeFileSync } from 'node:fs'
const out = process.argv[2]
const key = readFileSync(process.argv[3], 'utf8').trim()
const url = process.argv[4] ?? 'http://localhost:4174/'
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, acceptDownloads: true })
const page = await ctx.newPage()
const errors = []
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
await page.goto(url)
await page.evaluate(() => localStorage.clear())
await page.reload()
await page.waitForTimeout(800)
if (await page.$('.welcome')) await page.click('text=Explore the example home')
await page.waitForTimeout(1000)
await page.click('.plan-badge')
await page.click('text=I have a license key')
await page.fill('#license-key', 'THR1.garbage.key')
await page.click('button:has-text("Activate")')
await page.waitForTimeout(200)
console.log('bad key:', await page.locator('.paywall-key .error').textContent())
await page.fill('#license-key', key)
await page.click('button:has-text("Activate")')
await page.waitForTimeout(400)
console.log('badge:', await page.locator('.plan-badge').textContent())
// Branding
await page.click('button:has-text("Project")')
await page.fill('#brand-company', 'Northwind Homes')
await page.fill('#brand-contact', '555-0100 · northwind.example')
const [dl] = await Promise.all([page.waitForEvent('download', { timeout: 20000 }), page.click('text=Save floor plan image')])
await dl.saveAs(`${out}/plan-studio.png`)
console.log('plan export (studio):', dl.suggestedFilename())
// Presentation
await page.click('.view-switch >> text=3D')
await page.waitForTimeout(1500)
await page.click('.bar3d >> text=Present')
await page.waitForTimeout(4500)
await page.screenshot({ path: `${out}/present-1.png` })
await page.click('button:has-text("Daytime")')
await page.click('[aria-label="Next view"]')
await page.waitForTimeout(4500)
await page.screenshot({ path: `${out}/present-2.png` })
await page.keyboard.press('Escape')
await page.waitForTimeout(800)
console.log('back in editor:', await page.locator('.topbar').count())
await page.reload()
await page.waitForTimeout(1500)
console.log('badge after reload:', await page.locator('.plan-badge').textContent())
console.log(errors.join('\n') || 'no errors')
await browser.close()
