import { chromium } from 'playwright'
const out = process.argv[2]
const img = process.argv[3]
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('pageerror', (e) => console.log('pageerror: ' + e.message))
await page.goto('http://localhost:4173/')
await page.waitForTimeout(800)
if (await page.$('.welcome')) await page.click('text=Start from scratch')
await page.click('.view-switch >> text=2D')
await page.keyboard.press('Escape')
await page.click('.panel-tabs >> text=Levels')
await page.setInputFiles('#underlay-file', img)
await page.waitForTimeout(800)
const box = await (await page.$('.plan-svg')).boundingBox()
const before = await page.evaluate(() => { const s = window.__threshold.store.getState(); return null })
await page.mouse.click(box.x + box.width * 0.3, box.y + box.height * 0.5)
await page.mouse.click(box.x + box.width * 0.6, box.y + box.height * 0.5)
await page.waitForTimeout(200)
await page.fill('#calib-len', '40')
await page.click('text=Set scale')
await page.waitForTimeout(500)
await page.screenshot({ path: `${out}/80-underlay.png` })
console.log('mode after', await page.evaluate(() => document.querySelector('.underlay-bar') ? 'bar visible' : 'bar closed'))
await browser.close()
