// Checks design versions: save one free, a second asks for Pro, going back restores the design and undo returns.
// Usage: node scripts/versions-check.mjs <out dir>   (preview on :4173)
import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const p = await (await b.newContext({ viewport: { width: 1280, height: 900 }, serviceWorkers: 'block' })).newPage()
const errors = []
p.on('pageerror', (e) => errors.push(e.message))
await p.goto('http://localhost:4173/')
await p.evaluate(() => { localStorage.setItem('threshold:welcomed', '1'); localStorage.setItem('threshold:lowq', '1') })
await p.reload()
await p.waitForTimeout(1200)
await p.click('.panel-tabs >> text=Project')
const rooms = () => p.evaluate(() => window.__threshold.store.getState().project.levels.reduce((s, l) => s + l.rooms.length, 0))
await p.fill('#version-name', 'Original')
await p.click('button:has-text("Save version")')
await p.waitForTimeout(300)
const before = await rooms()
// Change the design: drop the upper floor's rooms.
await p.evaluate(() => window.__threshold.store.getState().apply((pr) => ({ ...pr, levels: pr.levels.map((l, i) => (i === 1 ? { ...l, rooms: [] } : l)) })))
const changed = await rooms()
await p.click('button:has-text("Save version")')
await p.waitForTimeout(300)
console.log('second save as free user opens:', await p.locator('#paywall-title').textContent().catch(() => '-'))
await p.keyboard.press('Escape')
await p.click('.version-row:has-text("Original") >> text=Go back')
await p.click('.version-row .is-armed')
await p.waitForTimeout(300)
const restored = await rooms()
await p.keyboard.press('Control+z')
await p.waitForTimeout(300)
console.log(`rooms: before ${before} | changed ${changed} | after going back ${restored} | after undo ${await rooms()}`)
await p.locator('.field:has-text("Versions of this design")').first().screenshot({ path: `${process.argv[2]}/versions.png` })
console.log(errors.join('\n') || 'no errors')
await b.close()
