import { chromium } from 'playwright'
const out = process.argv[2]
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const errors = []
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
await page.goto('http://localhost:4173/')
// The electrical layout is a Pro feature: run as a Pro trial.
await page.evaluate(() => localStorage.setItem('threshold:trial', String(Date.now())))
await page.reload()
await page.waitForTimeout(800)
if (await page.$('.welcome')) await page.click('text=Explore the example home')
await page.waitForTimeout(1200)
await page.click('.view-switch >> text=2D')
await page.click('text=Wire all rooms')
await page.waitForTimeout(500)
console.log(await page.locator('.toast').first().textContent().catch(() => 'no toast'))
const checks = await page.$$eval('.check-item', (els) => els.map((e) => e.textContent))
console.log('checks', JSON.stringify(checks))
await page.click('.zoom-btns [aria-label="Zoom in"]')
await page.click('.zoom-btns [aria-label="Zoom in"]')
await page.waitForTimeout(300)
await page.screenshot({ path: `${out}/wire-plan.png` })
await page.click('.view-options .icon-btn')
await page.click('text=Electrical (outlets')
await page.click('.view-options .icon-btn')
await page.waitForTimeout(300)
await page.screenshot({ path: `${out}/wire-plan-hidden.png` })
console.log(errors.join('\n') || 'no errors')
await browser.close()
